-- 코드를 입력하세요
SELECT YEAR(O.SALES_DATE) YEAR,
        MONTH(O.SALES_DATE) MONTH,
        GENDER,
        COUNT(DISTINCT O.USER_ID) USERS
FROM USER_INFO U
JOIN ONLINE_SALE O ON U.USER_ID = O.USER_ID
WHERE REGEXP_LIKE(GENDER, '0|1')
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER
;