SELECT
	YEAR(S.SALES_DATE) YEAR,
	MONTH(S.SALES_DATE) MONTH,
	COUNT(DISTINCT(S.USER_ID)) PUCHASED_USERS,
	ROUND(COUNT(DISTINCT(S.USER_ID)) /
            (SELECT
                COUNT(DISTINCT(USER_ID))
                FROM USER_INFO
                WHERE YEAR(JOINED) = '2021')
        , 1) PUCHASED_RATIO
FROM
	USER_INFO I
LEFT OUTER JOIN
	ONLINE_SALE S ON I.USER_ID = S.USER_ID
WHERE
	I.JOINED LIKE '2021%' AND S.USER_ID IS NOT NULL
GROUP BY
	YEAR(S.SALES_DATE), MONTH(S.SALES_DATE)
ORDER BY
	YEAR(S.SALES_DATE), MONTH(S.SALES_DATE)
;