SELECT
    MONTH(START_DATE) MONTH, CAR_ID, COUNT(CAR_ID) RECORDS
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE
    MONTH(START_DATE) BETWEEN 8 AND 10
-- WHERE절에서는 월별로 분류하지 않고 ID별로만 묶어서 확인, 월별 출력은 메인 쿼리에서 설정    
AND CAR_ID IN (
    SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE MONTH(START_DATE) BETWEEN 8 AND 10
    GROUP BY CAR_ID HAVING COUNT(CAR_ID) > 4
) 
GROUP BY
    MONTH, CAR_ID
ORDER BY
   MONTH, CAR_ID DESC
;