-- 코드를 입력하세요
SELECT DISTINCT(H.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR R
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON R.CAR_ID = H.CAR_ID
WHERE R.CAR_TYPE LIKE '세단'
AND MONTH(H.START_DATE) = '10'
ORDER BY H.CAR_ID DESC
;